Repository astrolabsoftware/fink-science-portal, pull requests merged in 2020-11, with the labels that each got.

#1 Towards 0.2: adding pyLIMA, allowing interactive lightcurve, and several layout fixes
  Procfile
  README.md
  apps/__init__.py
  apps/about.py
  apps/cards.py
  apps/explorer.py
  apps/grafink.py
  apps/home.py
  apps/mulens_helper.py
  apps/plotting.py
  apps/summary.py
  assets/cnrs.png
  assets/footer.css
  assets/home.css
  assets/lsstfr.png
  assets/ztf.png
  requirements.txt
Labels: bug, enhancement, layout

#19 Add upper limits in lightcurve (difference magnitude)
  apps/plotting.py
  apps/summary.py
  apps/utils.py
Labels: lightcurve

#21 [Classification] Update the criteria to label alerts
  apps/explorer.py
  apps/utils.py
Labels: classification

#22 Add cross-match to SDSS
  apps/cards.py
Labels: crossmatch

#23 Allow to display microlensing fit for single-band
  apps/plotting.py
Labels: bug, microlensing

#25 Add radioitem to the SN view to change units
  apps/cards.py
  apps/explorer.py
  apps/plotting.py
Labels: bug, supernovae

#31 Fix typos in explorer background
  apps/explorer.py
Labels: documentation

#38 Improve documentation for explorer
  apps/explorer.py
  assets/home.css
Labels: documentation, explorer

#39 Reset button
  apps/explorer.py
Labels: explorer

#40 Update GH link, and improve layout
  index.py
Labels: documentation

#41 capitalize Simbad class name before sorting
  apps/explorer.py
Labels: explorer

#42 Add a limit on ndethist<20 for early SNe class
  apps/utils.py
Labels: classification, supernovae

#44 Unify cutout callbacks
  apps/cards.py
  apps/plotting.py
Labels: bug, cutouts

#46 Separate labels and values for simbad types
  apps/explorer.py
Labels: bug, crossmatch

#48 Trigger the query only if the reset button is not pressed.
  apps/explorer.py
Labels: enhancement

#50 [var/micro] Remove empty axes to show the doc at first
  apps/cards.py
  apps/plotting.py
Labels: microlensing, variable

#52 Update hover to display MJD value
  apps/plotting.py
Labels: lightcurve

#56 Bump Portal version to 0.2
  apps/__init__.py
Labels: release

#58 Fix typo in the mulens class name
  apps/utils.py
Labels: bug

#64 New service: xmatch
  apps/cards.py
  apps/home.py
  apps/xmatch.py
  assets/home.css
  index.py
Labels: xmatch
