Repository astrolabsoftware/fink-science-portal, pull requests merged in 2021-03, with the labels that each got.

#118 cutout_plotting_improvement
  apps/plotting.py
Labels: cutouts, visualisation

#121 Fix new TNS URL
  apps/cards.py
Labels: external, supernovae

#120 Enable cutout data transfer
  apps/api.py
  apps/utils.py
Labels: cutouts, public API

#127 Display valid measurements contained in history
  apps/cards.py
  apps/plotting.py
  apps/summary.py
Labels: lightcurve, visualisation

#129 Update the portal with Kilonova search
  apps/api.py
  apps/cards.py
  apps/explorer.py
  apps/utils.py
  apps/xmatch.py
  assets/fink_types.csv
Labels: classification

#130 Cutout service: online!
  apps/api.py
  apps/plotting.py
  apps/utils.py
Labels: cutouts, public API

#132 SSO view
  apps/cards.py
  apps/explorer.py
  apps/plotting.py
  apps/summary.py
  apps/utils.py
  requirements.txt
Labels: sso
