Repository astrolabsoftware/fink-science-portal, pull requests merged in 2023-12, with the labels that each got.

#530 Adjust UI code to be properly responsive
  app.py
  apps/api/api.py
  apps/cards.py
  apps/gw.py
  apps/mulens/cards.py
  apps/plotting.py
  apps/query_cluster.py
  apps/statistics.py
  apps/summary.py
  apps/supernovae/cards.py
  apps/utils.py
  apps/varstars/cards.py
  assets/home.css
  assets/theme.css
  index.py
  telemetry.py
Labels: enhancement, layout, cutouts, hbase, code quality

#540 Update documentation for Data Transfer
  apps/query_cluster.py
Labels: documentation

#542 Improve SSO resolver
  apps/api/doc.py
  apps/api/utils.py
  tests/api_resolver_test.py
  tests/api_ssocand_test.py
Labels: hbase, sso, resolver

#545 Make the TNS and SSO resolver case-insensitive
  apps/api/utils.py
  tests/api_resolver_test.py
Labels: resolver

#543 Data release photometry for lightcurve panel
  app.py
  apps/cards.py
  apps/plotting.py
  apps/summary.py
  apps/utils.py
Labels: enhancement, lightcurve, color-evolution, ZTF data release
